"""ML3 — Annotation format (REQUIREMENTS.md §7 ML3, [shared]).

A typed, versioned schema for per-frame labels covering every surface this layer
must learn to read: detection boxes, fine classification, ownership, health,
fog-of-war cells, and minimap blips. Labels may come from a human annotator or be
generated by the ground-truth exporter (ML2, D6); either way they share this
format so the model team and the eval harness (ML8) consume one shape.

The format is expressed entirely in domain value objects (``ScreenBBox``,
``EntityKind``, ``Ownership``, ``FogState`` …) so an annotation converts cleanly
into the same ``Detections`` the ``PerceptionModel`` port emits — letting the eval
harness score predictions against labels with no impedance mismatch.

Offline-only: annotations are training/eval artifacts, never read at inference.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from zero_ad_eyes.domain.confidence import Confidence, Provenance
from zero_ad_eyes.domain.detections import Detection, Detections
from zero_ad_eyes.domain.geometry import ScreenBBox, WorldPoint
from zero_ad_eyes.domain.minimap import FogState
from zero_ad_eyes.domain.taxonomy import EntityKind, Ownership, Phase, ResourceType

ANNOTATION_SCHEMA_VERSION = "0.1.0"


class DetectionLabel(BaseModel):
    """A labelled on-screen entity: box + class + ownership + health (§4.3)."""

    model_config = ConfigDict(frozen=True)

    kind: EntityKind
    bbox: ScreenBBox
    entity_type: str | None = None  # fine taxonomy label when legible
    ownership: Ownership = Ownership.UNKNOWN
    health: float | None = Field(default=None, ge=0.0, le=1.0)

    def to_detection(self) -> Detection:
        """Project this label into the model port's ``Detection`` value object.

        Tagged ``ENGINE_GT`` provenance and full confidence: it is ground truth.
        """

        return Detection(
            kind=self.kind,
            bbox=self.bbox,
            entity_type=self.entity_type,
            confidence=Confidence.certain(Provenance.ENGINE_GT),
        )


class MinimapBlipLabel(BaseModel):
    """A labelled minimap dot in world space with its owner (§4.4)."""

    model_config = ConfigDict(frozen=True)

    world_pos: WorldPoint
    ownership: Ownership = Ownership.UNKNOWN


class FogCellLabel(BaseModel):
    """Visibility state of one minimap/grid cell (§4.4 / §4.5)."""

    model_config = ConfigDict(frozen=True)

    cell_x: int = Field(ge=0)
    cell_y: int = Field(ge=0)
    state: FogState


class HudLabel(BaseModel):
    """Labelled HUD readouts for a frame (§4.2)."""

    model_config = ConfigDict(frozen=True)

    stockpiles: dict[ResourceType, int] = Field(default_factory=dict)
    population_current: int | None = Field(default=None, ge=0)
    population_cap: int | None = Field(default=None, ge=0)
    phase: Phase = Phase.UNKNOWN


class FrameAnnotation(BaseModel):
    """The complete label set for one captured frame."""

    model_config = ConfigDict(frozen=True)

    frame_id: int = Field(ge=0)
    timestamp: float | None = None
    image_path: str | None = None  # links back to a CaptureEntry (ML1)
    detections: tuple[DetectionLabel, ...] = ()
    minimap_blips: tuple[MinimapBlipLabel, ...] = ()
    fog_cells: tuple[FogCellLabel, ...] = ()
    hud: HudLabel | None = None

    def to_detections(self) -> Detections:
        """The detection labels as a port-shaped ``Detections`` for this frame."""

        return Detections(
            frame_id=self.frame_id,
            items=tuple(label.to_detection() for label in self.detections),
        )


class AnnotationSet(BaseModel):
    """A versioned collection of per-frame annotations, with load/save."""

    model_config = ConfigDict(frozen=True)

    schema_version: str = ANNOTATION_SCHEMA_VERSION
    annotations: tuple[FrameAnnotation, ...] = ()

    def __len__(self) -> int:
        return len(self.annotations)

    def by_frame_id(self) -> dict[int, FrameAnnotation]:
        """Index annotations by frame id (last wins on duplicates)."""

        return {annotation.frame_id: annotation for annotation in self.annotations}

    def save(self, path: Path) -> None:
        path.write_text(self.model_dump_json(indent=2), encoding="utf-8")

    @classmethod
    def load(cls, path: Path) -> AnnotationSet:
        return cls.model_validate_json(path.read_text(encoding="utf-8"))
